import {
  faUtensils,
  faUser,
  faStore,
  faSignOutAlt,
  faPlus,
  faTrash,
  faEdit,
  faCheckCircle,
  faTimesCircle,
  faSearch,
  faCircleNotch,
  faShoppingCart,
  faPhone,
  faMinus,
  faPenToSquare,
  faTrashCan,
  faArrowLeft,
  faExclamationCircle,
  faInfoCircle,
  faCamera,
  faImage,
  faPlusCircle,
  faClipboardList,
  faClose,
  faLocation,
  faCircle,
  faArrowRight,
  faReceipt,
  faNoteSticky,
  faCheck,
  faBagShopping,
  faChevronDown,
  faArrowsRotate,
  faTruck,
  faCopy,
  faBars,
  faChevronLeft,
  faBowlRice,
  faEyeSlash,
  faEye,
  faHistory,
  faFilter,
  faUserCheck,
  faLocationArrow,
  faLocationDot,
  faTag,
  faEnvelope,
  faClockRotateLeft,
  faHandHoldingDollar,
} from '@fortawesome/free-solid-svg-icons';

import { faWhatsapp } from '@fortawesome/free-brands-svg-icons';

export const Icons = {
  live: faClockRotateLeft,
  percent: faHandHoldingDollar,
  envelope: faEnvelope,
  tag: faTag,
  locationArrow: faLocationArrow,
  locationDot: faLocationDot,
  filter: faFilter,
  history: faHistory,
  user: faUser,
  userCheck: faUserCheck,
  eyeSlash: faEyeSlash,
  eye: faEye,
  bowl: faBowlRice,
  bars: faBars,
  copy: faCopy,
  truck: faTruck,
  refresh: faArrowsRotate,
  chevronLeft: faChevronLeft,
  chevronDown: faChevronDown,
  bagShopping: faBagShopping,
  check: faCheck,
  whatsapp: faWhatsapp,
  notes: faNoteSticky,
  receipt: faReceipt,
  arrowRight: faArrowRight,
  location: faLocation,
  circle: faCircle,
  checkCircle: faCheckCircle,
  close: faClose,
  menu: faClipboardList,
  camera: faCamera,
  image: faImage,
  logo: faUtensils,
  success: faCheckCircle,
  error: faExclamationCircle,
  info: faInfoCircle,
  back: faArrowLeft,
  editPen: faPenToSquare,
  trashCan: faTrashCan,
  phone: faPhone,
  cart: faShoppingCart,
  profile: faUser,
  kitchen: faStore,
  logout: faSignOutAlt,
  addCircled: faPlusCircle,
  delete: faTrash,
  edit: faEdit,
  inStock: faCheckCircle,
  outOfStock: faTimesCircle,
  search: faSearch,
  spinner: faCircleNotch,
  plus: faPlus,
  minus: faMinus,
  infoCircled: faInfoCircle,
};
